//
//  ViewController.swift
//  Tip Calculator
//
//  Created by Elijah Felder on 12/7/24.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var inputTextField: UITextField!
    @IBOutlet weak var totalCustomLabel: UILabel!
    @IBOutlet weak var tipCustomLabel: UILabel!
    @IBOutlet weak var customTipPercentSlider: UISlider!
    @IBOutlet weak var customTipPercentLabel: UILabel!
    @IBOutlet weak var billAmountLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        //Reinforce that the initial tip percent is 15%
        customTipPercentSlider.value = 15
        
        //Select the TextField so keypad displays when the view loads
        inputTextField.becomeFirstResponder()
    }

    @IBAction func calculateTip(_ sender: Any) {
        //Creation of variables to be used in this method or function
        var decimal100: Double
        decimal100 = 100.0
        var customPercent: Double
        var billAmount: Double
        var inputDouble: Double
        
        //get the user input and store it in a variable
        let inputString = inputTextField.text
        
        //convert the value entered (string) to a double
        inputDouble = Double((inputString! as NSString).floatValue)
        
        //convert slider value to a decimal number and store in a variable
        let sliderValue = Int(customTipPercentSlider.value)
        
        //convert the slider value set up by the user to percent
        customPercent = Double(sliderValue) / decimal100
        
        //Identify who did generate the event. Was the slider?
        if sender is UISlider
        {
            //the thumb has been moved by the user, so update the label with the new custom percent
            customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value: customPercent), number: NumberFormatter.Style.percent)
        }
        
        //If there is a bill amount, calculate the new tip and total
        //Please pay attention that there is a negative (!) in front of the control inputString!
        if !inputString!.isEmpty
        {
            //convert the billAmount to add the decmial point
            billAmount = inputDouble / decimal100
            
            //Now we check if the event was generated by the TextField
            if sender is UITextField
            {
                //Update the billAmount with the currency format
                billAmountLabel.text = " " + formatAsCurrency(number: billAmount)
            }
            
            //Now, we calculate and display the tip and the total with currency format
            let customTip = billAmount * customPercent
            tipCustomLabel.text = formatAsCurrency(number: customTip)
            totalCustomLabel.text = formatAsCurrency(number: billAmount + customTip)
        }
        else
        {
            //We clear all the labels
            billAmountLabel.text = " "
            customTipPercentLabel.text = NumberFormatter.localizedString(from: NSNumber(value: customPercent), number: NumberFormatter.Style.percent)
            tipCustomLabel.text = " "
            totalCustomLabel.text = " "
        }
    }
    
}

//Global utility functions
//Convert a numberic value to a localized currency string
func formatAsCurrency(number: Double) -> String
{
    return NumberFormatter.localizedString(from: NSNumber(value: number), number: NumberFormatter.Style.currency)
}
